#!/usr/bin/env python3
"""
First-run setup for Trading Bot executable.
Prompts user for Telegram credentials and saves to config_local.py
"""
import os
import sys

def get_executable_dir():
    """Get the directory where the executable is located."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))

def config_local_exists():
    """Check if config_local.py exists with valid values."""
    config_path = os.path.join(get_executable_dir(), 'config_local.py')
    if not os.path.exists(config_path):
        return False
    try:
        with open(config_path, 'r') as f:
            content = f.read()
            required_fields = ['BOT_TOKEN', 'API_ID', 'API_HASH', 'OWNER_CHAT_ID', 'SCRAPER_PHONE']
            if all(field in content for field in required_fields):
                if 'Paste your' not in content and 'your_' not in content:
                    return True
    except:
        pass
    return False

def run_first_time_setup():
    """Run the first-time setup wizard."""
    print("\n" + "="*60)
    print("   TRADING BOT - FIRST TIME SETUP")
    print("="*60)
    print("\nWelcome! This appears to be your first time running the bot.")
    print("You need to provide your Telegram credentials to continue.\n")
    
    print("WHERE TO GET THESE:")
    print("  - BOT_TOKEN: Create a bot with @BotFather on Telegram")
    print("  - API_ID & API_HASH: https://my.telegram.org/apps")
    print("  - OWNER_CHAT_ID: Message @userinfobot on Telegram")
    print("  - PHONE NUMBER: Your Telegram account phone number\n")
    
    while True:
        print("-"*40)
        bot_token = input("Enter your BOT_TOKEN: ").strip()
        if not bot_token:
            print("BOT_TOKEN cannot be empty. Please try again.")
            continue
            
        api_id = input("Enter your API_ID (numbers only): ").strip()
        if not api_id.isdigit():
            print("API_ID must be a number. Please try again.")
            continue
            
        api_hash = input("Enter your API_HASH: ").strip()
        if not api_hash:
            print("API_HASH cannot be empty. Please try again.")
            continue
            
        owner_chat_id = input("Enter your OWNER_CHAT_ID (your Telegram user ID): ").strip()
        if not owner_chat_id.lstrip('-').isdigit():
            print("OWNER_CHAT_ID must be a number. Please try again.")
            continue
        
        print("\n" + "-"*40)
        print("TELEGRAM USER AUTHENTICATION")
        print("The bot needs to log into your Telegram account to monitor channels.")
        print("-"*40)
        
        scraper_phone = input("Enter your PHONE NUMBER (with country code, e.g. +1234567890): ").strip()
        if not scraper_phone:
            print("Phone number cannot be empty. Please try again.")
            continue
        if not scraper_phone.startswith('+'):
            scraper_phone = '+' + scraper_phone
        
        has_2fa = input("Do you have 2FA enabled on Telegram? (yes/no): ").strip().lower()
        scraper_password = ""
        if has_2fa in ['yes', 'y']:
            scraper_password = input("Enter your 2FA PASSWORD (or press Enter to be prompted later): ").strip()
        
        print("\n" + "-"*40)
        print("Please confirm your settings:")
        print(f"  BOT_TOKEN: {bot_token[:10]}...{bot_token[-5:]}")
        print(f"  API_ID: {api_id}")
        print(f"  API_HASH: {api_hash[:5]}...{api_hash[-5:]}")
        print(f"  OWNER_CHAT_ID: {owner_chat_id}")
        print(f"  PHONE NUMBER: {scraper_phone}")
        print(f"  2FA PASSWORD: {'[SET]' if scraper_password else '[NOT SET - will prompt if needed]'}")
        print("-"*40)
        
        confirm = input("\nIs this correct? (yes/no): ").strip().lower()
        if confirm in ['yes', 'y']:
            break
        print("\nLet's try again...\n")
    
    config_content = f'''"""
Local configuration overrides for Trading Bot.
This file is auto-generated by the first-run setup.
You can edit these values manually if needed.
"""

BOT_TOKEN = '{bot_token}'
API_ID = {api_id}
API_HASH = '{api_hash}'
OWNER_CHAT_ID = {owner_chat_id}
SCRAPER_PHONE = '{scraper_phone}'
SCRAPER_PASSWORD = '{scraper_password}'
'''
    
    config_path = os.path.join(get_executable_dir(), 'config_local.py')
    try:
        with open(config_path, 'w') as f:
            f.write(config_content)
        print(f"\nConfiguration saved to: {config_path}")
        print("\nYou can edit this file later to change your credentials.")
    except Exception as e:
        print(f"\nError saving configuration: {e}")
        print("Please make sure the bot has write permissions in its directory.")
        sys.exit(1)
    
    os.environ['BOT_TOKEN'] = bot_token
    os.environ['API_ID'] = api_id
    os.environ['API_HASH'] = api_hash
    os.environ['OWNER_CHAT_ID'] = owner_chat_id
    os.environ['SCRAPER_PHONE'] = scraper_phone
    os.environ['SCRAPER_PASSWORD'] = scraper_password
    
    print("\n" + "="*60)
    print("   CONFIG SAVED!")
    print("   Next: You'll be prompted for a Telegram verification code.")
    print("="*60 + "\n")
    
    return True

def check_and_run_setup():
    """Check if setup is needed and run it."""
    if not config_local_exists():
        run_first_time_setup()
    else:
        exec_dir = get_executable_dir()
        config_path = os.path.join(exec_dir, 'config_local.py')
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location("config_local", config_path)
            if spec is None or spec.loader is None:
                raise ImportError("Could not load config_local.py")
            config_local = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(config_local)
            
            if hasattr(config_local, 'BOT_TOKEN'):
                os.environ['BOT_TOKEN'] = str(config_local.BOT_TOKEN)
            if hasattr(config_local, 'API_ID'):
                os.environ['API_ID'] = str(config_local.API_ID)
            if hasattr(config_local, 'API_HASH'):
                os.environ['API_HASH'] = str(config_local.API_HASH)
            if hasattr(config_local, 'OWNER_CHAT_ID'):
                os.environ['OWNER_CHAT_ID'] = str(config_local.OWNER_CHAT_ID)
            if hasattr(config_local, 'SCRAPER_PHONE'):
                os.environ['SCRAPER_PHONE'] = str(config_local.SCRAPER_PHONE)
            if hasattr(config_local, 'SCRAPER_PASSWORD'):
                os.environ['SCRAPER_PASSWORD'] = str(config_local.SCRAPER_PASSWORD)
        except Exception as e:
            print(f"Warning: Could not load config_local.py: {e}")
            run_first_time_setup()

if __name__ == "__main__":
    check_and_run_setup()
    print("Setup complete! You can now run main.py to start the bot.")
